### PR TITLE
fixed build for Jekyll 3.0 and corrected loading.gif

### PR DESCRIPTION
**Pull request by patmuk**
moved all pages to /pages
and all template files to /assets
## separated template and site content in /assets

made pagenation, highlighter and markdown Jekyll 3.0 compatible
and
fixed reference to and location of
loading.git (wasn't found)

### CODE REVIEW

**Comment by patmuk** [comment]
fixed separation, now baser works as well

**Comment by madforjekyll** [comment]
@patmuk Thank you for your contribution.

**Comment by patmuk** [comment]
@madforjekyll You are very welcome. Thanks for the awesome template! If you need help to sort out certain issues just let me know.

**Comment by sunbliss** [comment]
@patmuk The template has been updated.

 I kept most of the structure the way you pushed it and the only difference is that I left the 'writing' section outside the pages folder, because I did not like the way the url was being rendered. 

The css has been refreshed and polished and hopefully you will find good use of it.

Have a wonderful weekend.

**Pull request merged**
